spring:
  application:
    name: eureka-server-7001

server:
  port: 7001

eureka:
  instance:
    hostname: eureka7001.com
  client:
    service-url:
      #eureka服务地址，如果是集群的话，需要指定其他集群的eureka地址，注册eureka中心其他的eureka服务器
      defaultZone: http://eureka7002:7002/eureka
      #不注册自己
    register-with-eureka: false
    #不拉取服务
    fetch-registry: false

